version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4901:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
